# Generated by Django 4.1.5 on 2023-01-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(default='', verbose_name='note'),
        ),
    ]
