# Generated by Django 5.1.5 on 2025-01-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_note'),
        ('members', '0009_member_entry_date_member_exit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AddField(
            model_name='event',
            name='requirement_type',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory Event'), ('VOLUNTARY', 'Voluntary Event'), ('ADDITIONAL', 'Additional Event'), ('INSTRUCTOR', 'Instructor Event')], default='MANDATORY', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='members.member', verbose_name='member'),
        ),
    ]
