version: '3.8'

services:
  web:
    build: .
    command: gunicorn jfm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/jfm/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
