# Generated by Django 4.1.5 on 2023-01-23 22:44

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(default=announcements.models.Announcement.in_2_weeks, verbose_name='end time'),
        ),
    ]
