# Generated by Django 4.1.5 on 2023-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_square',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='members/square'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='members/org'),
        ),
    ]
