# Generated by Django 4.1.5 on 2023-01-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_options_alter_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='instructor'),
        ),
    ]
