# Generated by Django 4.1.5 on 2023-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
    ]
