# Generated by Django 4.1.5 on 2023-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_image_square_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_passport',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='members/passport'),
        ),
    ]
