# Generated by Django 4.1.5 on 2023-01-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_image_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['lastname']},
        ),
    ]
