# Generated by Django 4.1.5 on 2023-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['lastname'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/org', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_passport',
            field=models.ImageField(blank=True, null=True, upload_to='members/passport', verbose_name='passwort image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_square',
            field=models.ImageField(blank=True, null=True, upload_to='members/square', verbose_name='square image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
    ]
