# Generated by Django 4.2 on 2023-04-06 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='entry date'),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='exit date'),
        ),
    ]
