name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Turn server off
        working-directory: ${{secrets.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S docker-compose down
      - name: Pull new image
        working-directory: ${{secrets.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S docker-compose pull
      - name: Start server
        working-directory: ${{secrets.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S docker-compose up -d
      - name: Run migration
        working-directory: ${{secrets.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S docker-compose exec -T jfm python manage.py migrate