name: Deployment

on:
  push

jobs:
  deployment:
    runs-on: self-hosted
    environment: ficorede
    steps:
      - name: deploy
        working-directory: ${{vars.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S echo $PWD