name: FTP Deployment to test env

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install python requirements
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --deploy --dev
      - name: Install node requirements
        run: npm install
        working-directory: frontend
      - name: Create static backend files
        working-directory: backend
        run: pipenv run python manage.py collectstatic
      - name: Move static files into httpdocs
        run: |
          mkdir -p httpdocs
          mv -v backend/static httpdocs
      - name: Create / touch restart.txt for passenger restart
        run: |
          mkdir backend/tmp
          touch backend/tmp/restart.txt
          current_date=$(date +"%m-%d-%Y")
          echo "$current_date" > backend/tmp/restart.txt
      - name: Build Angular App
        run: npm run build
        working-directory: frontend
      - name: Move frontend files into httpdocs
        run: |
          mv -v frontend/dist/frontend/browser/de/* httpdocs
      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/__pycache__/**
