name: Deployment

on:
  push

jobs:
  deployment:
    runs-on: self-hosted
    environment: ficorede
    steps:
      - name: Turn server off
        working-directory: ${{vars.CONTAINTER_PATH}}
        run: echo -e "${{secrets.PASSWORD}}\n" | sudo -S docker-compose down
      - name: Pull new image
        working-directory: ${{vars.CONTAINTER_PATH}}
        run: sudo docker-compose pull
      - name: Start server
        working-directory: ${{vars.CONTAINTER_PATH}}
        run: sudo docker-compose up -d
      - name: Run migration
        working-directory: ${{vars.CONTAINTER_PATH}}
        run: sudo docker-compose exec -T jfm python manage.py migrate