name: Docker Compose Push

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create dummy env-prod
      run: mv ./.env.prod.sample ./.env.prod
    - name: Build the Docker image
      run: docker-compose build
    - name: Run django tests in docker
      run: docker-compose run web python manage.py test
    - name: Log in to Docker Hub
      uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image
      run: docker-compose push