name: Docker Compose Push

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create dummy env-prod
      working-directory: backend
      run: mv ./.env.prod.sample ./.env.prod
    - name: Build the Docker image
      working-directory: backend
      run: docker-compose build
    - name: Run django tests in docker
      working-directory: backend
      run: docker-compose run web python manage.py test
    - name: Log in to Docker Hub
      uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image
      working-directory: backend
      run: docker-compose push