name: Docker Compose Push

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create dummy env-prod
      run: mv ./.env.prod.sample ./.env.prod
    - name: Build the Docker image
      run: docker-compose build
    - name: Run django tests in docker
      run: docker-compose run web python manage.py test
    - name: Log in to Docker Hub
      uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image
      run: docker-compose push